spring:
    datasource:
        stockhistory:
            name: stockhistory
            jdbc-url: jdbc:mysql://127.0.0.1:3306/stock_history?characterEncoding=UTF-8
            username: root
            password: 123456
            # 使用druid数据源
            type: com.alibaba.druid.pool.DruidDataSource
            driver-class-name: com.mysql.jdbc.Driver
            filters: stat,log4j
            maxActive: 50
            initialSize: 5
            maxWait: 60000
            minIdle: 1
            timeBetweenEvictionRunsMillis: 60000
            minEvictableIdleTimeMillis: 300000
            validationQuery: select 'x'
            testWhileIdle: true
            #cachePrepStmts: true 开启二级缓存
            testOnBorrow: true
            testOnReturn: true
            poolPreparedStatements: true
            maxOpenPreparedStatements: 20