spring:
    datasource:
        technical:
            name: stockhistory
            jdbc-url: jdbc:mysql://127.0.0.1:3306/stock_history?characterEncoding=UTF-8
            username: root
            password: 123456
            # 使用druid数据源
            type: com.alibaba.druid.pool.DruidDataSource
            driver-class-name: com.mysql.jdbc.Driver
            filters: stat,log4j
            maxActive: 50
            initialSize: 5
            maxWait: 60000
            minIdle: 1
            timeBetweenEvictionRunsMillis: 60000
            minEvictableIdleTimeMillis: 300000
            validationQuery: select 'x'
            testWhileIdle: true
            #cachePrepStmts: true 开启二级缓存
            testOnBorrow: true
            testOnReturn: true
            poolPreparedStatements: true
            maxOpenPreparedStatements: 20
        fundmental:
            name: fundmental
            jdbc-url: jdbc:mysql://127.0.0.1:3306/stock_fundmental?characterEncoding=UTF-8
            username: root
            password: 123456
            # 使用druid数据源
            type: com.alibaba.druid.pool.DruidDataSource
            driver-class-name: com.mysql.jdbc.Driver
            filters: stat,log4j
            maxActive: 50
            initialSize: 5
            maxWait: 60000
            minIdle: 1
            timeBetweenEvictionRunsMillis: 60000
            minEvictableIdleTimeMillis: 300000
            validationQuery: select 'x'
            testWhileIdle: true
            #cachePrepStmts: true 开启二级缓存
            testOnBorrow: true
            testOnReturn: true
            poolPreparedStatements: true
            maxOpenPreparedStatements: 20
        stockconfig:
            name: stockconfig
            jdbc-url: jdbc:mysql://127.0.0.1:3306/stock_config?characterEncoding=UTF-8
            username: root
            password: 123456
            # 使用druid数据源
            type: com.alibaba.druid.pool.DruidDataSource
            driver-class-name: com.mysql.jdbc.Driver
            filters: stat,log4j
            maxActive: 50
            initialSize: 5
            maxWait: 60000
            minIdle: 1
            timeBetweenEvictionRunsMillis: 60000
            minEvictableIdleTimeMillis: 300000
            validationQuery: select 'x'
            testWhileIdle: true
            #cachePrepStmts: true 开启二级缓存
            testOnBorrow: true
            testOnReturn: true
            poolPreparedStatements: true
            maxOpenPreparedStatements: 20
        stock:
            name: stock
            jdbc-url: jdbc:mysql://127.0.0.1:3306/stock?characterEncoding=UTF-8
            username: root
            password: 123456
            # 使用druid数据源
            type: com.alibaba.druid.pool.DruidDataSource
            driver-class-name: com.mysql.jdbc.Driver
            filters: stat,log4j
            maxActive: 50
            initialSize: 5
            maxWait: 60000
            minIdle: 1
            timeBetweenEvictionRunsMillis: 60000
            minEvictableIdleTimeMillis: 300000
            validationQuery: select 'x'
            testWhileIdle: true
            #cachePrepStmts: true 开启二级缓存
            testOnBorrow: true
            testOnReturn: true
            poolPreparedStatements: true
            maxOpenPreparedStatements: 20
        gross:
            jdbc-url: jdbc:mysql://127.0.0.1:3306/stock_gross?characterEncoding=UTF-8
            username: root
            password: 123456
            # 使用druid数据源
            type: com.alibaba.druid.pool.DruidDataSource
            driver-class-name: com.mysql.jdbc.Driver
            filters: stat,log4j
            maxActive: 50
            initialSize: 5
            maxWait: 60000
            minIdle: 1
            timeBetweenEvictionRunsMillis: 60000
            minEvictableIdleTimeMillis: 300000
            validationQuery: select 'x'
            testWhileIdle: true
            #cachePrepStmts: true 开启二级缓存
            testOnBorrow: true
            testOnReturn: true
            poolPreparedStatements: true
            maxOpenPreparedStatements: 20
    redis:
            host: localhost
            port: 6379
            timeout: 20000
            poolmaxactive: 8
            poolminidle: 0
            poolmaxidle: 8
            poolmaxwait: 20000
redis-cluster:
      hosts: 127.0.0.1:6379
      maxtotal: 10000
      maxidle: 100
      maxwaitmillis: 1000